### ISSUE TITLE
MultiStart - signature

### ISSUE THREAD

**Issue by tankista01** [StranikS-Scan/WorldOfTanks-MultiStart#1]
Hi, 

i found that Multi start stop working. Found that signature for 64-bit WoT in version 1.21.0.0 is [0F 84 8A 00 00 00 E8] so after change it to [E9 8B 00 00 00 00 E8] all works again. Could you add this signature to signature64.list?

**Comment by StranikS-Scan** [comment]
Added a new signature. Thank you
